server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  profiles:
    include: oauth

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#  config: src/main/resources/logback-local.xml

springdoc:
  packages-to-scan: com.testchatbot
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

chatgpt:
  model: gpt-3.5-turbo
  api-key: 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
  max-token: 250